apiVersion: v1
kind: Pod
metadata:
  name: nginx-t
  labels:
    key: app
    value: blue
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"
